package dotnet.system.runtime.interopServices.comTypes;
enum ADVF {
	ADVF_NODATA;
	ADVF_PRIMEFIRST;
	ADVF_ONLYONCE;
	ADVF_DATAONSTOP;
	ADVFCACHE_NOHANDLER;
	ADVFCACHE_FORCEBUILTIN;
	ADVFCACHE_ONSAVE;
}