package dotnet.system.runtime.interopServices.comTypes;
enum PARAMFLAG {
	PARAMFLAG_NONE;
	PARAMFLAG_FIN;
	PARAMFLAG_FOUT;
	PARAMFLAG_FLCID;
	PARAMFLAG_FRETVAL;
	PARAMFLAG_FOPT;
	PARAMFLAG_FHASDEFAULT;
	PARAMFLAG_FHASCUSTDATA;
}