package dotnet.system.runtime.interopServices.comTypes;
enum VARFLAGS {
	VARFLAG_FREADONLY;
	VARFLAG_FSOURCE;
	VARFLAG_FBINDABLE;
	VARFLAG_FREQUESTEDIT;
	VARFLAG_FDISPLAYBIND;
	VARFLAG_FDEFAULTBIND;
	VARFLAG_FHIDDEN;
	VARFLAG_FRESTRICTED;
	VARFLAG_FDEFAULTCOLLELEM;
	VARFLAG_FUIDEFAULT;
	VARFLAG_FNONBROWSABLE;
	VARFLAG_FREPLACEABLE;
	VARFLAG_FIMMEDIATEBIND;
}