package dotnet.system.globalization;
@:native('System.Globalization.CultureAndRegionInfoBuilder') extern class CultureAndRegionInfoBuilder {
	function new(cultureName:String, flags:dotnet.system.globalization.CultureAndRegionModifiers):Void;
	var AvailableCalendars(default,default):dotnet.system.globalization.Calendar;
	var CompareInfo(default,default):dotnet.system.globalization.CompareInfo;
	var ConsoleFallbackUICulture(default,default):dotnet.system.globalization.CultureInfo;
	var CultureEnglishName(default,default):String;
	var CultureName(default,null):String;
	var CultureNativeName(default,default):String;
	var CultureTypes(default,null):dotnet.system.globalization.CultureTypes;
	var CurrencyEnglishName(default,default):String;
	var CurrencyNativeName(default,default):String;
	var GeoId(default,default):Int;
	var GregorianDateTimeFormat(default,default):dotnet.system.globalization.DateTimeFormatInfo;
	var IetfLanguageTag(default,default):String;
	var IsMetric(default,default):Bool;
	var ISOCurrencySymbol(default,default):String;
	var IsRightToLeft(default,default):Bool;
	var KeyboardLayoutId(default,default):Int;
	var LCID(default,null):Int;
	var NumberFormat(default,default):dotnet.system.globalization.NumberFormatInfo;
	var Parent(default,default):dotnet.system.globalization.CultureInfo;
	var RegionEnglishName(default,default):String;
	var RegionName(default,null):String;
	var RegionNativeName(default,default):String;
	var TextInfo(default,default):dotnet.system.globalization.TextInfo;
	var ThreeLetterISOLanguageName(default,default):String;
	var ThreeLetterISORegionName(default,default):String;
	var ThreeLetterWindowsLanguageName(default,default):String;
	var ThreeLetterWindowsRegionName(default,default):String;
	var TwoLetterISOLanguageName(default,default):String;
	var TwoLetterISORegionName(default,default):String;
	static function CreateFromLdml(xmlFileName:String):dotnet.system.globalization.CultureAndRegionInfoBuilder;
	function Equals(obj:Dynamic):Bool;
	function GetHashCode():Int;
	function GetType():cs.system.Type;
	function LoadDataFromCultureInfo(culture:dotnet.system.globalization.CultureInfo):Void;
	function LoadDataFromRegionInfo(region:dotnet.system.globalization.RegionInfo):Void;
	function Register():Void;
	function Save(filename:String):Void;
	function ToString():String;
	static function Unregister(cultureName:String):Void;
}